server.port=8083

# JWT
jwt.secret=my-super-long-secret-key-that-is-at-least-32-chars!!
jwt.access.expiration.ms=900000
jwt.refresh.expiration.ms=604800000

# MongoDB
spring.data.mongodb.uri=mongodb://root:secret@${MONGO_HOST:localhost}:27017/jwt_demo?authSource=admin

# AI Model Service (Friend's model URL)
ai.model.url=https://draw-union-mouse-dependence.trycloudflare.com

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tripplanner143@gmail.com
# For Gmail, you must generate an "App Password" from your Google Account settings
spring.mail.password=zberjofwxrowujqk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
